-- Keep organization deletion compatible with the management-audit triggers.
--
-- Deleting an organization cascades to memberships, branches, templates and
-- schedule periods. Their AFTER DELETE audit triggers run after the parent
-- organization row is already gone. Writing a new audit row at that point
-- violates audit_logs_organization_id_fkey (correctly ON DELETE CASCADE) and
-- rolls the entire organization deletion back.
--
-- A deleted tenant has no audit-log owner or retention surface, so skip audit
-- writes generated by that tenant's own FK cascade. Direct child deletion
-- still sees the organization and remains audited.

create or replace function private.write_management_audit_log()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  row_value jsonb := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  target_organization_id uuid;
  target_entity_id uuid;
  safe_metadata jsonb;
begin
  target_organization_id := case
    when tg_table_name = 'organizations' then (row_value ->> 'id')::uuid
    else (row_value ->> 'organization_id')::uuid
  end;
  target_entity_id := (row_value ->> 'id')::uuid;

  if target_organization_id is null or target_entity_id is null then
    return case when tg_op = 'DELETE' then old else new end;
  end if;

  if tg_op = 'DELETE'
     and not exists (
       select 1
       from public.organizations organization_row
       where organization_row.id = target_organization_id
     ) then
    return old;
  end if;

  safe_metadata := jsonb_strip_nulls(jsonb_build_object(
    'operation', lower(tg_op),
    'role', row_value ->> 'role',
    'status', row_value ->> 'status',
    'name', case
      when tg_table_name in ('organizations','branches','shift_templates')
      then row_value ->> 'name'
      else null
    end,
    'year', row_value ->> 'year',
    'month', row_value ->> 'month'
  ));

  insert into public.audit_logs (
    organization_id,
    actor_user_id,
    action,
    entity_type,
    entity_id,
    metadata
  ) values (
    target_organization_id,
    (select auth.uid()),
    tg_table_name || '.' || lower(tg_op),
    tg_table_name,
    target_entity_id,
    safe_metadata
  );

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

revoke all on function private.write_management_audit_log() from public, anon, authenticated;

-- Leave requests were the only direct tenant-owned table whose organization
-- FK did not cascade. Closing a business must remove those rows with the rest
-- of the tenant rather than turn account deletion into another FK failure.
alter table public.leave_requests
  drop constraint if exists leave_requests_organization_id_fkey,
  add constraint leave_requests_organization_id_fkey
    foreign key (organization_id)
    references public.organizations(id)
    on delete cascade;

comment on function private.write_management_audit_log()
  is 'Records safe metadata for direct management changes; skips child deletes caused by deletion of the owning organization.';
